# Generated by Django 3.2.8 on 2021-11-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='post_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
