# Generated by Django 3.2.7 on 2021-10-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
