# Generated by Django 3.2.8 on 2021-11-23 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 14, 21, 26, 195863, tzinfo=utc)),
        ),
    ]
