# Generated by Django 3.2.8 on 2021-11-23 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_chatmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 15, 24, 7, 245211, tzinfo=utc)),
        ),
    ]
