# Generated by Django 3.2.8 on 2021-11-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_chatmessage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
    ]
