# Generated by Django 3.2.8 on 2021-11-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_chatmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
