# Generated by Django 3.2.8 on 2021-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_auto_20211112_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='disabled_forum',
            field=models.BooleanField(default=False),
        ),
    ]
