# Generated by Django 3.2.8 on 2021-10-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20171022_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
    ]
