# Generated by Django 3.2.8 on 2021-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='post_time',
            field=models.TimeField(),
        ),
    ]
