# Generated by Django 3.2.7 on 2021-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta_ship',
            name='can_add_assignments',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='can_add_resources',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='can_add_students',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ta_ship',
            name='can_notify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
